Add director
bannovdaniil/java-filmorate pull request #14
Opened 2022-07-22 22:16 UTC by Anton-Morozov-Java-3-2

Добавлена функциональность режиссёры. Тесты проходят.

2022-07-22 22:47 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (sortBy.equals("year")) return filmService.getFilmsByDirectorsSortedByDate(id);
В контроллере не должно быть никакой логики, от слова совсем.

2022-07-22 22:48 UTC, bannovdaniil reviewed
Большая проделанная работа, еще и в таком темпе!

2022-07-22 23:01 UTC, bannovdaniil commented on src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
в базах принято ID задавать как ИМЯБАЗЫ_ID
director_id

2022-07-22 23:12 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "MERGE INTO `DIRECTORS` (ID, NAME) VALUES (?, ?);";
изначально проект заточен под PostGresSQL так покрайне мере говорилось в какомто из спринтов. это потом чтобы не мучались перешли на H2.
MERGE меняй на UPDATE
MERGE нету  PostGreSQL
https://habr.com/ru/company/postgrespro/blog/412605/

2022-07-22 23:13 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "SELECT ID, NAME FROM `DIRECTORS`;";
хорошая практика писать полностью имена полей из таблицы.

2022-07-22 23:14 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "MERGE INTO FILM_DIRECTORS (film_id, director_id) values ( ?, ? );";
-> UPDATE

2022-07-22 23:21 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "SELECT F.FILM_ID, COUNT(*) C FROM FILMS F LEFT JOIN LIKES L ON F.FILM_ID = L.FILM_ID" +
в таблице есть поле специальное Like используй вместо COUNT(*) работать будет в разы быстрее.

2022-07-22 23:25 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoStorageImpl.java
>          }
вроде сдесь не хватает.
         film.setDirectors(directorStorage.getDirectorsByFilm(film.getId()));

2022-07-22 23:31 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorStorage.java
> +    List<Director> saveDirectorsOfFilm(Long film_id, List<Director> directors);
List<Director> saveDirectorsOfFilm(Long film_id, List<Director> directors);
декомпозицию параметров надо
List<Director> saveDirectorsOfFilm(Film film);
а в методе уже доставать необходимые поля.

2022-07-22 23:41 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dto/DtoDirector.java
> +    private int id;
int не может быть NULL априори, если хочшь это проверять делай Integer

2022-07-22 23:46 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Long film_id : directorStorage.getFilmsByDirectorOrderByLikes(id)) {
а если сразу из базы поднять List<Film> без дополнительных циклов?

select * from filmw where film_id in (select film_id from film_directors where director_id = ?)

2022-07-22 23:47 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Long film_id : directorStorage.getFilmsByDirectorOrderByDate(id)) {
тоже самое

2022-07-23 06:32 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "SELECT F.FILM_ID, COUNT(*) C FROM FILMS F LEFT JOIN LIKES L ON F.FILM_ID = L.FILM_ID" +
Ок, поправлю, но думаю это дублирование информации и из базы лучше убрать это поле.

2022-07-23 06:38 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorStorage.java
> +    List<Director> saveDirectorsOfFilm(Long film_id, List<Director> directors);
Не понял, что ты имел ввиду. Метод сохраняет в базу список режиссёров фильма, аргументы метода - список режиссёров.

2022-07-23 06:38 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "MERGE INTO FILM_DIRECTORS (film_id, director_id) values ( ?, ? );";
Ок

2022-07-23 06:42 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "MERGE INTO `DIRECTORS` (ID, NAME) VALUES (?, ?);";
ок

2022-07-23 06:43 UTC, Anton-Morozov-Java-3-2 commented on src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ок

2022-07-23 06:49 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (sortBy.equals("year")) return filmService.getFilmsByDirectorsSortedByDate(id);
Ок, но тут идут идёт обработка параметров запроса, это не бизнес логика.

2022-07-23 06:50 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dto/DtoDirector.java
> +    private int id;
По-моему  null это отсутствие id в теле запроса. Ок, сделаю Integer.

2022-07-23 06:53 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Long film_id : directorStorage.getFilmsByDirectorOrderByLikes(id)) {
Я за разделение ответственности. За фильмами хожу через логику описанную FilmStorage. Если добавятся поля в Film нужно будет делать изменения в логике FilmStorage и DirectorStorage.

2022-07-23 06:58 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (sortBy.equals("year")) return filmService.getFilmsByDirectorsSortedByDate(id);
это слой контролеров тут ничего не должно быть.
Controller — отвечает за взаимодействие с пользователем посредством IO (ввод-вывод).
ни слова не сказанно, что он делает выбор.
например вот статья:
https://habr.com/ru/post/493430/

его обязанность получить из вне и ровно в таком-же виде отдать дальше.

все ветвления происходят в других слоях.

2022-07-23 07:03 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "SELECT F.FILM_ID, COUNT(*) C FROM FILMS F LEFT JOIN LIKES L ON F.FILM_ID = L.FILM_ID" +
это оптимизация о ней говорили на лекциях, Чтобы показать сколько у фильма лайков, а там их предположим миллион, придется занять приличное машинное время, посчитав все user_id. А так когда приходит Like, делается +1, когда лайк убирают делается -1. Но и знать кто ставит лайки нам тоже необходимо. Поэтому есть поле Likes независимое от базы лайков пользователя.

2022-07-23 07:10 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorStorage.java
> +    List<Director> saveDirectorsOfFilm(Long film_id, List<Director> directors);
вызов твоего метода выглядит так:
        List<Director> directorsOfFilm = directorStorage.saveDirectorsOfFilm(film.getId(), film.getDirectors());
два раза дергается film.getId(), и  film.getDirectors())
это можно сделать и внутри метода. Тем самым повысить читаемость кода.

        List<Director> directorsOfFilm = directorStorage.saveDirectorsOfFilm(film);

2022-07-23 07:11 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dto/DtoDirector.java
> +    private int id;
если INT Отсутствует в запросе то это 0.
если Integer отсуствует то это Null

2022-07-23 07:23 UTC, bannovdaniil commented
> Добавлена функциональность режиссёры. Тесты проходят.
Постарался дать более расширенные комментарии.

2022-07-23 07:27 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Long film_id : directorStorage.getFilmsByDirectorOrderByLikes(id)) {
тоесть по твоей логике в FilmStorage не используется ничего из других Storage? ни genres, Likes, Users?

2022-07-23 07:29 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Long film_id : directorStorage.getFilmsByDirectorOrderByLikes(id)) {
Работа с данным должна происходить в слое Данных, а не в слои бизнес логики.

2022-07-23 08:08 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (sortBy.equals("year")) return filmService.getFilmsByDirectorsSortedByDate(id);
Ок

2022-07-23 08:11 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +        String sql = "SELECT F.FILM_ID, COUNT(*) C FROM FILMS F LEFT JOIN LIKES L ON F.FILM_ID = L.FILM_ID" +
Ок

2022-07-23 08:13 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorStorage.java
> +    List<Director> saveDirectorsOfFilm(Long film_id, List<Director> directors);
Ок

2022-07-23 08:22 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Long film_id : directorStorage.getFilmsByDirectorOrderByLikes(id)) {
Не понял о чём ты. FilmStorage в слое работы с данными. Его обязанность работать с объектами Film (crud). Ты хочешь чтобы я создавал объекты Film в DirectorStorage?

2022-07-23 19:32 UTC, bannovdaniil requested changes
Хорошо сделаная работа, остались небольшие замечания.

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/RequestParamNotValid.java
> +public class RequestParamNotValid extends Exception {
Тут правильно унаследованное исключение, проверяемое, мы же проверяаем наличие сами, чтобы пробрасывалось по слоям.

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/DirectorNotFoundException.java
> +public class DirectorNotFoundException extends RuntimeException {
Тут НЕ правильно унаследованное исключение, непроверяемые, но мы какраз таки проверяем и сами выбрасываем его.

https://javarush.ru/groups/posts/1944-iskljuchenija-checked-unchecked-i-svoi-sobstvennihe

Exceptions — это, собственно, исключения: исключительная, незапланированная ситуация, которая произошла при работе программы.

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +    public DirectorDaoStorageImpl(JdbcTemplate jdbcTemplate) {
вместо этого воспользуйся @RequiredArgsConstructor

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +    public boolean isExists(int id) {
не совсем удачное имя, оно используется во вне.

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +    public List<Director> getDirectorsByFilm(Long film_id) {
это хорошее имя отражает суть происходящего.

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public DirectorService(DirectorStorage directorStorage) {
воспользуйся 
@RequiredArgsConstructor

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +@Component
это не @Component 
это
@Repository

https://ask-dev.ru/info/1316/whats-the-difference-between-component-repository-service-annotations-in-spring

2022-07-23 19:32 UTC, bannovdaniil commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +@Service
тут верная анотация.

2022-07-23 21:08 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +@Component
ок

2022-07-23 21:09 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public DirectorService(DirectorStorage directorStorage) {
ок

2022-07-23 21:09 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +    public boolean isExists(int id) {
во вне не используется, сделал private

2022-07-23 21:09 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoStorageImpl.java
> +    public DirectorDaoStorageImpl(JdbcTemplate jdbcTemplate) {
ок

2022-07-23 21:09 UTC, Anton-Morozov-Java-3-2 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/DirectorNotFoundException.java
> +public class DirectorNotFoundException extends RuntimeException {
ок

2022-07-23 22:28 UTC, bannovdaniil approved these changes

2022-07-23 22:28 UTC, merged